In [1]:
import numpy as np
import csv

In [2]:
def openCSV(filename):
    with open(filename, newline='') as file:
        reader = csv.DictReader(file)
        result = np.empty((0,6))
        for row in reader:
            headerRow = np.array([[row['Open'], row['High'], row['Low'], row['Close'], row['Adj Close'], row['Volume']]])
            result = np.append(result, headerRow, axis=0)
    return result.astype('float32')



In [7]:
np.set_printoptions(formatter={'float': '{: 6.2f}'.format})

In [22]:
appleStockPrices2016 = openCSV('AAPL-2016.csv')
print(appleStockPrices2016)

[[ 102.61  105.37  102.00  105.35  100.27  67649400.00]
 [ 105.75  105.85  102.41  102.71  97.76  55791000.00]
 [ 100.56  102.37  99.87  100.70  95.85  68457400.00]
 ...
 [ 115.59  116.52  115.59  116.52  113.37  14249500.00]
 [ 116.52  117.80  116.49  117.26  114.09  18296900.00]
 [ 117.52  118.02  116.20  116.76  113.61  20905900.00]]


In [11]:
january = appleStockPrices2016[:20]
print(january)
january.shape

[[ 102.61  105.37  102.00  105.35  100.27  67649400.00]
 [ 105.75  105.85  102.41  102.71  97.76  55791000.00]
 [ 100.56  102.37  99.87  100.70  95.85  68457400.00]
 [ 98.68  100.13  96.43  96.45  91.80  81094400.00]
 [ 98.55  99.11  96.76  96.96  92.29  70798000.00]
 [ 98.97  99.06  97.34  98.53  93.78  49739400.00]
 [ 100.55  100.69  98.84  99.96  95.14  49154200.00]
 [ 100.32  101.19  97.30  97.39  92.70  62439600.00]
 [ 97.96  100.48  95.74  99.52  94.73  63170100.00]
 [ 96.20  97.71  95.36  97.13  92.45  79010000.00]
 [ 98.41  98.65  95.50  96.66  92.00  53087700.00]
 [ 95.10  98.19  93.42  96.79  92.13  72334400.00]
 [ 97.06  97.88  94.94  96.30  91.66  52161500.00]
 [ 98.63  101.46  98.37  101.42  96.53  65800500.00]
 [ 101.52  101.53  99.21  99.44  94.65  51794500.00]
 [ 99.93  100.88  98.07  99.99  95.17  75077000.00]
 [ 96.04  96.63  93.34  93.42  88.92  133369696.00]
 [ 93.79  94.52  92.39  94.09  89.56  55678800.00]
 [ 94.79  97.34  94.35  97.34  92.65  64416500.00]
 [ 96.4

(20, 6)

In [12]:
january[0][5] = 100
print(january)

[[ 102.61  105.37  102.00  105.35  100.27  100.00]
 [ 105.75  105.85  102.41  102.71  97.76  55791000.00]
 [ 100.56  102.37  99.87  100.70  95.85  68457400.00]
 [ 98.68  100.13  96.43  96.45  91.80  81094400.00]
 [ 98.55  99.11  96.76  96.96  92.29  70798000.00]
 [ 98.97  99.06  97.34  98.53  93.78  49739400.00]
 [ 100.55  100.69  98.84  99.96  95.14  49154200.00]
 [ 100.32  101.19  97.30  97.39  92.70  62439600.00]
 [ 97.96  100.48  95.74  99.52  94.73  63170100.00]
 [ 96.20  97.71  95.36  97.13  92.45  79010000.00]
 [ 98.41  98.65  95.50  96.66  92.00  53087700.00]
 [ 95.10  98.19  93.42  96.79  92.13  72334400.00]
 [ 97.06  97.88  94.94  96.30  91.66  52161500.00]
 [ 98.63  101.46  98.37  101.42  96.53  65800500.00]
 [ 101.52  101.53  99.21  99.44  94.65  51794500.00]
 [ 99.93  100.88  98.07  99.99  95.17  75077000.00]
 [ 96.04  96.63  93.34  93.42  88.92  133369696.00]
 [ 93.79  94.52  92.39  94.09  89.56  55678800.00]
 [ 94.79  97.34  94.35  97.34  92.65  64416500.00]
 [ 96.47  96

In [14]:
firstFive = appleStockPrices2016[:5]
print(firstFive)

[[ 102.61  105.37  102.00  105.35  100.27  100.00]
 [ 105.75  105.85  102.41  102.71  97.76  55791000.00]
 [ 100.56  102.37  99.87  100.70  95.85  68457400.00]
 [ 98.68  100.13  96.43  96.45  91.80  81094400.00]
 [ 98.55  99.11  96.76  96.96  92.29  70798000.00]]


In [17]:
closeHigh = appleStockPrices2016[3].max()
print(closeHigh)

81094400.0


In [18]:
closeLow = appleStockPrices2016[3].min()
print(closeLow)

91.803276


In [28]:
firstFiveHigh = appleStockPrices2016[:,[1,2]][0:5]
print(firstFiveHigh)


[[ 105.37]
 [ 105.85]
 [ 102.37]
 [ 100.13]
 [ 99.11]]
