In [13]:
import numpy as np
import csv

In [2]:
def openCSV(filename):
    with open(filename, newline='') as file:
        reader = csv.DictReader(file)
        result = np.empty((0,6))
        for row in reader:
            headerRow = np.array([[row['Open'], row['High'], row['Low'], row['Close'], row['Adj Close'], row['Volume']]])
            result = np.append(result, headerRow, axis=0)
    return result.astype('float32')



In [5]:
appleStockPrices2016 = openCSV('AAPL-2016.csv')
print(appleStockPrices2016)

[[ 102.61  105.37  102.00  105.35  100.27  67649400.00]
 [ 105.75  105.85  102.41  102.71  97.76  55791000.00]
 [ 100.56  102.37  99.87  100.70  95.85  68457400.00]
 ...
 [ 115.59  116.52  115.59  116.52  113.37  14249500.00]
 [ 116.52  117.80  116.49  117.26  114.09  18296900.00]
 [ 117.52  118.02  116.20  116.76  113.61  20905900.00]]


In [4]:
np.set_printoptions(formatter={'float': '{: 6.2f}'.format})

In [24]:
firstFiveHigh = appleStockPrices2016[:,[1,2]]
#print(firstFiveHigh)
projectionMatrix = np.array([[1.1, 0.0],[0.0 ,1.2]])
projection = np.dot(firstFiveHigh,projectionMatrix)
print(projection[:5])

[[ 115.91  122.40]
 [ 116.43  122.89]
 [ 112.61  119.84]
 [ 110.14  115.72]
 [ 109.02  116.11]]
