In [5]:
import numpy as np
import csv

In [6]:
def openCSV(filename):
    with open(filename, newline='') as file:
        reader = csv.DictReader(file)
        result = np.empty((0,6))
        for row in reader:
            headerRow = np.array([[row['Open'], row['High'], row['Low'], row['Close'], row['Adj Close'], row['Volume']]])
            result = np.append(result, headerRow, axis=0)
    return result.astype('float32')



In [26]:
appleStockPrices2016 = openCSV('AAPL-2016.csv')
print(appleStockPrices2016)

[[ 102.61  105.37  102.00  105.35  100.27  67649400.00]
 [ 105.75  105.85  102.41  102.71  97.76  55791000.00]
 [ 100.56  102.37  99.87  100.70  95.85  68457400.00]
 ...
 [ 115.59  116.52  115.59  116.52  113.37  14249500.00]
 [ 116.52  117.80  116.49  117.26  114.09  18296900.00]
 [ 117.52  118.02  116.20  116.76  113.61  20905900.00]]


In [27]:
appleStockPrices2017 = openCSV('AAPL-2017.csv')
print(appleStockPrices2017)

[[ 115.80  116.33  114.76  116.15  113.01  28781900.00]
 [ 115.85  116.51  115.75  116.02  112.89  21118100.00]
 [ 115.92  116.86  115.81  116.61  113.46  22193600.00]
 ...
 [ 170.80  171.47  169.68  170.57  168.63  33185500.00]
 [ 170.10  170.78  169.71  170.60  168.66  21498200.00]
 [ 171.00  171.85  170.48  171.08  169.14  16480200.00]]


In [15]:
print('Total traded volume for AAPL 2016:',appleStockPrices2016[5].sum(axis=0))
print('Total traded volume for AAPL 2017:',appleStockPrices2017[5].sum(axis=0))

Total traded volume for AAPL 2016: 49739890.0
Total traded volume for AAPL 2017: 24462692.0


In [28]:
print('Change in total traded volume for AAPL 2017 to 2016:'
      ,appleStockPrices2017[5].sum(axis=0)-appleStockPrices2016[5].sum(axis=0))

Change in total traded volume for AAPL 2017 to 2016: -25277196.0


In [33]:
change = appleStockPrices2017-appleStockPrices2016
#print(change)
change[5].sum(axis=0)

-25277196.0

In [23]:
np.set_printoptions(formatter={'float': '{: 6.2f}'.format})

This tells NumPy to print floating point numbers with 6 spaces for the whole number part and 2 spaces for the fractional part.

**np.set_printoptions(formatter={'float': '{: 6.2f}'.format})**

You can reset the formatter using 
**np.set_printoptions().**

In [38]:
combined_years = np.concatenate((appleStockPrices2016,appleStockPrices2017),axis=0)
print(combined_years)

[[ 102.61  105.37  102.00  105.35  100.27  67649400.00]
 [ 105.75  105.85  102.41  102.71  97.76  55791000.00]
 [ 100.56  102.37  99.87  100.70  95.85  68457400.00]
 ...
 [ 170.80  171.47  169.68  170.57  168.63  33185500.00]
 [ 170.10  170.78  169.71  170.60  168.66  21498200.00]
 [ 171.00  171.85  170.48  171.08  169.14  16480200.00]]


In [40]:
np.savetxt('AAPL-2016_2017',combined_years, fmt='%10.2f',delimiter=',')